services:
  webserver:
    build: .
    entrypoint: /app/entrypoint.sh
    ports:
      - 7000:7000
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
